workflows:
  android-workflow:
    environment:
      flutter: 3.24.3
      android_signing:
        - Adel
    scripts:
      - script: flutter pub get
      - script: flutter pub run flutter_launcher_icons
      - script: flutter build appbundle --release
      - script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
